/*
 *  
 *
 *  
 *
 * OpenAPI spec version: 1.0.0-dsep-draft
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace BAP.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class CancellationReasonsMessage : IEquatable<CancellationReasonsMessage>
    { 
        /// <summary>
        /// Gets or Sets CancellationReasons
        /// </summary>

        [DataMember(Name="cancellation_reasons")]
        public List<Option> CancellationReasons { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CancellationReasonsMessage {\n");
            sb.Append("  CancellationReasons: ").Append(CancellationReasons).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((CancellationReasonsMessage)obj);
        }

        /// <summary>
        /// Returns true if CancellationReasonsMessage instances are equal
        /// </summary>
        /// <param name="other">Instance of CancellationReasonsMessage to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CancellationReasonsMessage other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    CancellationReasons == other.CancellationReasons ||
                    CancellationReasons != null &&
                    CancellationReasons.SequenceEqual(other.CancellationReasons)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (CancellationReasons != null)
                    hashCode = hashCode * 59 + CancellationReasons.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(CancellationReasonsMessage left, CancellationReasonsMessage right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(CancellationReasonsMessage left, CancellationReasonsMessage right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
