/*
 *  
 *
 *  
 *
 * OpenAPI spec version: 1.0.0-dsep-draft
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace BAP.Models
{ 
    /// <summary>
    /// Describes a quote
    /// </summary>
    [DataContract]
    public partial class Quotation : IEquatable<Quotation>
    { 
        /// <summary>
        /// Gets or Sets Price
        /// </summary>

        [DataMember(Name="price")]
        public Price Price { get; set; }

        /// <summary>
        /// Gets or Sets Breakup
        /// </summary>

        [DataMember(Name="breakup")]
        public List<QuotationBreakup> Breakup { get; set; }

        /// <summary>
        /// Gets or Sets Ttl
        /// </summary>

        [DataMember(Name="ttl")]
        public string Ttl { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Quotation {\n");
            sb.Append("  Price: ").Append(Price).Append("\n");
            sb.Append("  Breakup: ").Append(Breakup).Append("\n");
            sb.Append("  Ttl: ").Append(Ttl).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((Quotation)obj);
        }

        /// <summary>
        /// Returns true if Quotation instances are equal
        /// </summary>
        /// <param name="other">Instance of Quotation to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Quotation other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Price == other.Price ||
                    Price != null &&
                    Price.Equals(other.Price)
                ) && 
                (
                    Breakup == other.Breakup ||
                    Breakup != null &&
                    Breakup.SequenceEqual(other.Breakup)
                ) && 
                (
                    Ttl == other.Ttl ||
                    Ttl != null &&
                    Ttl.Equals(other.Ttl)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Price != null)
                    hashCode = hashCode * 59 + Price.GetHashCode();
                    if (Breakup != null)
                    hashCode = hashCode * 59 + Breakup.GetHashCode();
                    if (Ttl != null)
                    hashCode = hashCode * 59 + Ttl.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(Quotation left, Quotation right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Quotation left, Quotation right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
