/*
 *  
 *
 *  
 *
 * OpenAPI spec version: 1.0.0-dsep-draft
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace BAP.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class RatingAck : IEquatable<RatingAck>
    { 
        /// <summary>
        /// If feedback has been recorded or not
        /// </summary>
        /// <value>If feedback has been recorded or not</value>

        [DataMember(Name="feedback_ack")]
        public bool? FeedbackAck { get; set; }

        /// <summary>
        /// If rating has been recorded or not
        /// </summary>
        /// <value>If rating has been recorded or not</value>

        [DataMember(Name="rating_ack")]
        public bool? _RatingAck { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RatingAck {\n");
            sb.Append("  FeedbackAck: ").Append(FeedbackAck).Append("\n");
            sb.Append("  _RatingAck: ").Append(_RatingAck).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((RatingAck)obj);
        }

        /// <summary>
        /// Returns true if RatingAck instances are equal
        /// </summary>
        /// <param name="other">Instance of RatingAck to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RatingAck other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    FeedbackAck == other.FeedbackAck ||
                    FeedbackAck != null &&
                    FeedbackAck.Equals(other.FeedbackAck)
                ) && 
                (
                    _RatingAck == other._RatingAck ||
                    _RatingAck != null &&
                    _RatingAck.Equals(other._RatingAck)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (FeedbackAck != null)
                    hashCode = hashCode * 59 + FeedbackAck.GetHashCode();
                    if (_RatingAck != null)
                    hashCode = hashCode * 59 + _RatingAck.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(RatingAck left, RatingAck right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(RatingAck left, RatingAck right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
