///*
// * Beckn Core API
// *
// * Beckn Core API specification
// *
// * OpenAPI spec version: 1.0.0-dsep-draft
// * 
// * Generated by: https://github.com/swagger-api/swagger-codegen.git
// */
//using System;
//using System.Collections.Generic;
//using Microsoft.AspNetCore.Mvc;
//using Swashbuckle.AspNetCore.Annotations;
//using Swashbuckle.AspNetCore.SwaggerGen;
//using Newtonsoft.Json;
//using System.ComponentModel.DataAnnotations;
//using bpp.Attributes;
//using bpp.Security;
//using Microsoft.AspNetCore.Authorization;
//using bpp.Models;

//namespace bpp.Controllers
//{ 
//    /// <summary>
//    /// 
//    /// </summary>
//    [ApiController]
//    public class BAPMetaAPIsApiController : ControllerBase
//    { 
//        /// <summary>
//        /// 
//        /// </summary>
//        /// <remarks>Get cancellation reasons from the BPP</remarks>
//        /// <param name="body">List of cancellation reasons</param>
//        /// <response code="200">Acknowledgement of message received</response>
//        [HttpPost]
//        [Route("/cancellation_reasons")]
//        [Authorize(AuthenticationSchemes = ApiKeyAuthenticationHandler.SchemeName)]
//        [ValidateModelState]
//        [SwaggerOperation("CancellationReasonsPost")]
//        [SwaggerResponse(statusCode: 200, type: typeof(InlineResponse200), description: "Acknowledgement of message received")]
//        public virtual IActionResult CancellationReasonsPost([FromBody]CancellationReasonsBody body)
//        { 
//            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
//            // return StatusCode(200, default(InlineResponse200));
//            string exampleJson = null;
//            exampleJson = "{\n  \"message\" : {\n    \"ack\" : {\n      \"status\" : \"ACK\"\n    }\n  },\n  \"error\" : {\n    \"path\" : \"path\",\n    \"code\" : \"code\",\n    \"type\" : \"CONTEXT-ERROR\",\n    \"message\" : \"message\"\n  }\n}";
            
//                        var example = exampleJson != null
//                        ? JsonConvert.DeserializeObject<InlineResponse200>(exampleJson)
//                        : default(InlineResponse200);            //TODO: Change the data returned
//            return new ObjectResult(example);
//        }

//        /// <summary>
//        /// 
//        /// </summary>
//        /// <remarks>Get a list of categories for which feedback can be given by the BAP</remarks>
//        /// <param name="body">Array of categories for which feedback can be given by the BAP</param>
//        /// <response code="200">Acknowledgement of message received</response>
//        [HttpPost]
//        [Route("/feedback_categories")]
//        [Authorize(AuthenticationSchemes = ApiKeyAuthenticationHandler.SchemeName)]
//        [ValidateModelState]
//        [SwaggerOperation("FeedbackCategoriesPost")]
//        [SwaggerResponse(statusCode: 200, type: typeof(InlineResponse200), description: "Acknowledgement of message received")]
//        public virtual IActionResult FeedbackCategoriesPost([FromBody]FeedbackCategoriesBody body)
//        { 
//            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
//            // return StatusCode(200, default(InlineResponse200));
//            string exampleJson = null;
//            exampleJson = "{\n  \"message\" : {\n    \"ack\" : {\n      \"status\" : \"ACK\"\n    }\n  },\n  \"error\" : {\n    \"path\" : \"path\",\n    \"code\" : \"code\",\n    \"type\" : \"CONTEXT-ERROR\",\n    \"message\" : \"message\"\n  }\n}";
            
//                        var example = exampleJson != null
//                        ? JsonConvert.DeserializeObject<InlineResponse200>(exampleJson)
//                        : default(InlineResponse200);            //TODO: Change the data returned
//            return new ObjectResult(example);
//        }

//        /// <summary>
//        /// 
//        /// </summary>
//        /// <remarks>Get a feedback form from the BPP</remarks>
//        /// <param name="body">Feedback form sent by the BPP</param>
//        /// <response code="200">Acknowledgement of message received</response>
//        [HttpPost]
//        [Route("/feedback_form")]
//        [Authorize(AuthenticationSchemes = ApiKeyAuthenticationHandler.SchemeName)]
//        [ValidateModelState]
//        [SwaggerOperation("FeedbackFormPost")]
//        [SwaggerResponse(statusCode: 200, type: typeof(InlineResponse200), description: "Acknowledgement of message received")]
//        public virtual IActionResult FeedbackFormPost([FromBody]FeedbackFormBody body)
//        { 
//            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
//            // return StatusCode(200, default(InlineResponse200));
//            string exampleJson = null;
//            exampleJson = "{\n  \"message\" : {\n    \"ack\" : {\n      \"status\" : \"ACK\"\n    }\n  },\n  \"error\" : {\n    \"path\" : \"path\",\n    \"code\" : \"code\",\n    \"type\" : \"CONTEXT-ERROR\",\n    \"message\" : \"message\"\n  }\n}";
            
//                        var example = exampleJson != null
//                        ? JsonConvert.DeserializeObject<InlineResponse200>(exampleJson)
//                        : default(InlineResponse200);            //TODO: Change the data returned
//            return new ObjectResult(example);
//        }

//        /// <summary>
//        /// 
//        /// </summary>
//        /// <remarks>Get a list of categories that can be rated by the BAP</remarks>
//        /// <param name="body">Array of categories which can be rated</param>
//        /// <response code="200">Acknowledgement of message received</response>
//        [HttpPost]
//        [Route("/rating_categories")]
//        [Authorize(AuthenticationSchemes = ApiKeyAuthenticationHandler.SchemeName)]
//        [ValidateModelState]
//        [SwaggerOperation("RatingCategoriesPost")]
//        [SwaggerResponse(statusCode: 200, type: typeof(InlineResponse200), description: "Acknowledgement of message received")]
//        public virtual IActionResult RatingCategoriesPost([FromBody]RatingCategoriesBody body)
//        { 
//            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
//            // return StatusCode(200, default(InlineResponse200));
//            string exampleJson = null;
//            exampleJson = "{\n  \"message\" : {\n    \"ack\" : {\n      \"status\" : \"ACK\"\n    }\n  },\n  \"error\" : {\n    \"path\" : \"path\",\n    \"code\" : \"code\",\n    \"type\" : \"CONTEXT-ERROR\",\n    \"message\" : \"message\"\n  }\n}";
            
//                        var example = exampleJson != null
//                        ? JsonConvert.DeserializeObject<InlineResponse200>(exampleJson)
//                        : default(InlineResponse200);            //TODO: Change the data returned
//            return new ObjectResult(example);
//        }

//        /// <summary>
//        /// 
//        /// </summary>
//        /// <remarks>Get return reasons from the BPP</remarks>
//        /// <param name="body">List of return reasons</param>
//        /// <response code="200">Acknowledgement of message received</response>
//        [HttpPost]
//        [Route("/return_reasons")]
//        [Authorize(AuthenticationSchemes = ApiKeyAuthenticationHandler.SchemeName)]
//        [ValidateModelState]
//        [SwaggerOperation("ReturnReasonsPost")]
//        [SwaggerResponse(statusCode: 200, type: typeof(InlineResponse200), description: "Acknowledgement of message received")]
//        public virtual IActionResult ReturnReasonsPost([FromBody]ReturnReasonsBody body)
//        { 
//            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
//            // return StatusCode(200, default(InlineResponse200));
//            string exampleJson = null;
//            exampleJson = "{\n  \"message\" : {\n    \"ack\" : {\n      \"status\" : \"ACK\"\n    }\n  },\n  \"error\" : {\n    \"path\" : \"path\",\n    \"code\" : \"code\",\n    \"type\" : \"CONTEXT-ERROR\",\n    \"message\" : \"message\"\n  }\n}";
            
//                        var example = exampleJson != null
//                        ? JsonConvert.DeserializeObject<InlineResponse200>(exampleJson)
//                        : default(InlineResponse200);            //TODO: Change the data returned
//            return new ObjectResult(example);
//        }
//    }
//}
