///*
// * Beckn Core API
// *
// * Beckn Core API specification
// *
// * OpenAPI spec version: 1.0.0-dsep-draft
// * 
// * Generated by: https://github.com/swagger-api/swagger-codegen.git
// */
//using System;
//using System.Collections.Generic;
//using Microsoft.AspNetCore.Mvc;
//using Swashbuckle.AspNetCore.Annotations;
//using Swashbuckle.AspNetCore.SwaggerGen;
//using Newtonsoft.Json;
//using System.ComponentModel.DataAnnotations;
//using bpp.Attributes;
//using bpp.Security;
//using Microsoft.AspNetCore.Authorization;
//using bpp.Models;

//namespace bpp.Controllers
//{ 
//    /// <summary>
//    /// 
//    /// </summary>
//    [ApiController]
//    public class BecknGatewayBGApiController : ControllerBase
//    { 
//        /// <summary>
//        /// 
//        /// </summary>
//        /// <remarks>Send catalog</remarks>
//        /// <param name="body">TODO</param>
//        /// <response code="200">Acknowledgement of message received</response>
//        [HttpPost]
//        [Route("/on_search")]
//        [Authorize(AuthenticationSchemes = ApiKeyAuthenticationHandler.SchemeName)]
//        [ValidateModelState]
//        [SwaggerOperation("OnSearchPost")]
//        [SwaggerResponse(statusCode: 200, type: typeof(InlineResponse2001), description: "Acknowledgement of message received")]
//        public virtual IActionResult OnSearchPost([FromBody]OnSearchBody body)
//        { 
//            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
//            // return StatusCode(200, default(InlineResponse2001));
//            string exampleJson = null;
//            exampleJson = "{\n  \"message\" : {\n    \"ack\" : {\n      \"status\" : \"ACK\"\n    }\n  },\n  \"error\" : {\n    \"path\" : \"path\",\n    \"code\" : \"code\",\n    \"type\" : \"CONTEXT-ERROR\",\n    \"message\" : \"message\"\n  }\n}";
            
//                        var example = exampleJson != null
//                        ? JsonConvert.DeserializeObject<InlineResponse2001>(exampleJson)
//                        : default(InlineResponse2001);            //TODO: Change the data returned
//            return new ObjectResult(example);
//        }

//        /// <summary>
//        /// 
//        /// </summary>
//        /// <remarks>This allows a user to search for a) Jobs and Internships b) Trainings and Courses c)</remarks>
//        /// <param name="body">BAP searches for services</param>
//        /// <response code="200">Acknowledgement of message received</response>
//        [HttpPost]
//        [Route("/search")]
//        [Authorize(AuthenticationSchemes = ApiKeyAuthenticationHandler.SchemeName)]
//        [ValidateModelState]
//        [SwaggerOperation("SearchPost")]
//        [SwaggerResponse(statusCode: 200, type: typeof(InlineResponse200), description: "Acknowledgement of message received")]
//        public virtual IActionResult SearchPost([FromBody]SearchBody body)
//        { 
//            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
//            // return StatusCode(200, default(InlineResponse200));
//            string exampleJson = null;
//            exampleJson = "{\n  \"message\" : {\n    \"ack\" : {\n      \"status\" : \"ACK\"\n    }\n  },\n  \"error\" : {\n    \"path\" : \"path\",\n    \"code\" : \"code\",\n    \"type\" : \"CONTEXT-ERROR\",\n    \"message\" : \"message\"\n  }\n}";
            
//                        var example = exampleJson != null
//                        ? JsonConvert.DeserializeObject<InlineResponse200>(exampleJson)
//                        : default(InlineResponse200);            //TODO: Change the data returned
//            return new ObjectResult(example);
//        }
//    }
//}
